FROM maven:3.8.1-jdk-8

RUN apt-get update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -

RUN apt-get install -y nodejs

# accept the arguments from .Env (via compose file)
ARG PUID
ARG PGID
ARG USER

# Add the group (if not existing)
# then add the user to the numbered group
ARG USER_ID=1008
ARG GROUP_ID=1008
RUN groupadd -g $GROUP_ID actia && \
    useradd -u $USER_ID -g $GROUP_ID -G actia -m -d /home/actia -s /bin/sh actia

RUN chown actia:actia -R /home/actia/
